INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Alabama', 'Birmingham', -12);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'New York', 'Utica', 0);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Georgia', 'Atlanta', -9);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Ohio', 'Cleveland', 10);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Oklahoma', 'Tulsa', -1);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Tennessee', 'Memphis', -3);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'California', 'San Diego', -6);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Colorado', 'Boulder', 8);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Ohio', 'Cleveland', 10);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Georgia', 'Columbus', 7);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Hawaii', 'Honolulu', -3);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Florida', 'Jacksonville', -4);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Texas', 'Houston', 12);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Ohio', 'Toledo', -5);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Massachusetts', 'Boston', -2);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Oklahoma', 'Norman', -8);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Ohio', 'Canton', 0);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Florida', 'Jacksonville', -9);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'Ohio', 'Cleveland', 2);
INSERT into ubicacion (pais, estado, ciudad, huso) values ('United States', 'New York', 'White Plains', 11);
