package gui;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.JRadioButton;

public class Empleado extends JFrame{
	/**
	 * Autogenerated serialVersionUID for JFrame
	 */
	private static final long serialVersionUID = -2735425409835907346L;

	private Connection conn = null;
	private JTextField textField;
	private JTextField textField_1;
	private JTextField textField_2;
	private JTextField textField_3;
	private JTextField textField_4;
	private JTextField textField_5;
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Empleado window = new Empleado();
					window.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public Empleado() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		this.setBounds(250, 150, 500, 500);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		JPanel passPanel = new JPanel();
		passPanel.setLayout(null);
		passPanel.setBounds(0, 0, 500, 500);
		
		//Ciudad de Origen y Destino
		JLabel CO= new JLabel("Ciudad Origen:");
		JTextField CO2= new JTextField();
		CO2.setToolTipText("");
		JLabel CD= new JLabel("Ciudad Destino:");
		JTextField CD2= new JTextField();
		
		CO.setBounds(0, 0, 100, 20);
		CD.setBounds(0, 50, 100, 20);
		
		CO2.setBounds(0, 20, 100, 20);
		CO2.setVisible(true);
		CO2.setEditable(true);
		CO2.setFocusable(true);
		
		CD2.setBounds(0, 70 , 100, 20);
		CD2.setVisible(true);
		CD2.setEditable(true);
		CD2.setFocusable(true);
		
		//Vuelos de ida o ida y vuelta
		

		passPanel.add(CO);
		passPanel.add(CD);
		passPanel.add(CO2);
		passPanel.add(CD2);		

		getContentPane().add(passPanel);
		
		JSeparator separator = new JSeparator();
		separator.setBounds(0, 101, 984, 2);
		passPanel.add(separator);
		
		JSeparator separator_1 = new JSeparator();
		separator_1.setOrientation(SwingConstants.VERTICAL);
		separator_1.setBounds(110, 0, 2, 103);
		passPanel.add(separator_1);
		
		JRadioButton rdbtnNewRadioButton_1 = new JRadioButton("Vuelos de ida y vuelta");
		rdbtnNewRadioButton_1.setBounds(118, 49, 173, 23);
		passPanel.add(rdbtnNewRadioButton_1);
		
		JRadioButton rdbtnNewRadioButton = new JRadioButton("Vuelos de ida");
		rdbtnNewRadioButton.setBounds(118, 24, 173, 23);
		passPanel.add(rdbtnNewRadioButton);
		
		ButtonGroup bg = new ButtonGroup();
		bg.add(rdbtnNewRadioButton_1);
		bg.add(rdbtnNewRadioButton);
		
		JSeparator separator_2 = new JSeparator();
		separator_2.setOrientation(SwingConstants.VERTICAL);
		separator_2.setBounds(297, 0, 2, 103);
		passPanel.add(separator_2);
		
		JLabel lblFechaDeseadaPara = new JLabel("Fecha vuelo de ida");
		lblFechaDeseadaPara.setBounds(309, 3, 180, 14);
		passPanel.add(lblFechaDeseadaPara);
		
		JLabel lblSeleccioneUnaOpcin = new JLabel("Seleccione una opci\u00F3n:");
		lblSeleccioneUnaOpcin.setBounds(122, 3, 165, 14);
		passPanel.add(lblSeleccioneUnaOpcin);
		
		JLabel lblFechaVueloDe = new JLabel("Fecha vuelo de vuelta");
		lblFechaVueloDe.setBounds(309, 53, 180, 14);
		passPanel.add(lblFechaVueloDe);
		
		textField = new JTextField();
		textField.setToolTipText("");
		textField.setBounds(309, 25, 20, 20);
		passPanel.add(textField);
		textField.setColumns(10);
		
		textField_1 = new JTextField();
		textField_1.setColumns(10);
		textField_1.setBounds(339, 25, 20, 20);
		passPanel.add(textField_1);
		
		textField_2 = new JTextField();
		textField_2.setColumns(10);
		textField_2.setBounds(369, 25, 40, 20);
		passPanel.add(textField_2);
		
		textField_3 = new JTextField();
		textField_3.setToolTipText("");
		textField_3.setColumns(10);
		textField_3.setBounds(309, 70, 20, 20);
		passPanel.add(textField_3);
		
		textField_4 = new JTextField();
		textField_4.setToolTipText("");
		textField_4.setColumns(10);
		textField_4.setBounds(339, 70, 20, 20);
		passPanel.add(textField_4);
		
		textField_5 = new JTextField();
		textField_5.setToolTipText("");
		textField_5.setColumns(10);
		textField_5.setBounds(369, 70, 40, 20);
		passPanel.add(textField_5);
	}
}
